Repository pluginsGLPI/fields, pull requests merged in 2024-09, with the labels that each got.

#819 Fix(Core): fix bulk update for dropdown used in more than one container
  CHANGELOG.md
  inc/field.class.php
Labels: bug

#825 Feat(core): add ComputerVirtualMachine
  CHANGELOG.md
  inc/toolbox.class.php
Labels: enhancement

#831 Chore(i18n): update translations
  locales/en_GB.mo
  locales/en_GB.po
  locales/fields.pot
  locales/ru_RU.mo
  locales/ru_RU.po
Labels: i18n
