Repository pluginsGLPI/fields, pull requests merged in 2024-12, with the labels that each got.

#858 Fix(Core): Add entities_id and is_recursive fields to correctly filter data from the API
  CHANGELOG.md
  inc/abstractcontainerinstance.class.php
  templates/container.class.tpl
Labels: bug

#868 Prevent destroy
  CHANGELOG.md
  inc/field.class.php
Labels: bug

#875 Fix: API issue preventing multi-field updates
  CHANGELOG.md
  inc/container.class.php
Labels: bug

#878 Chore(i18n): update translations
  locales/en_GB.mo
  locales/en_GB.po
  locales/en_US.po
  locales/es_AR.po
  locales/es_EC.po
  locales/es_MX.po
  locales/fields.pot
  locales/fr_FR.po
  locales/hr_HR.po
  locales/ja_JP.mo
  locales/ja_JP.po
  locales/pt_BR.po
  locales/pt_PT.po
  locales/ro_RO.po
  locales/ru_RU.po
  locales/sk_SK.po
  locales/tr_TR.po
Labels: i18n

#857 fix: datatype number for search
  CHANGELOG.md
  inc/container.class.php
Labels: bug, need feedback
